import { z } from 'zod';

/**
 * `gitignore.render`, the pure half (video-structure plan §4D; design: brains `video-as-code/
 * video-gitignore-central-owner.md` §2–3). One generated block owns the ignore rules of every `v-*` brand repo, so the
 * seven hand-edited copies stop drifting. This file holds the rules and the text work and touches no disk, no clock and
 * no machine: the block is a pure function of (base version, brand key, overlay), byte-identical on every Mac (R8).
 * `gitignore.ts` reads and writes the files.
 *
 * Design notes where this departs from the design doc:
 *  - git has no trailing comments (`pattern # why` is one pattern), so a reason tag heads each group as a comment line
 *    instead of trailing each rule.
 *  - Order inside the block is fixed: the denies, then the base re-includes (`!`), then the few denies that must beat a
 *    re-include (machine-local files that are JSON), then the brand overlay in the order its file gives. `-trash/` and
 *    `-renders/` are directory rules, so no file re-include can reach inside them.
 */

/** Bump when the base rules change. The marker carries it, so a Mac on older rules shows as drift, not a silent rewrite. */
export const GITIGNORE_BASE_VERSION = 1;

export const GITIGNORE_BEGIN = '# >>> BEGIN generated by fli gitignore.render';
export const GITIGNORE_END = '# <<< END generated';

const Tag = z.string().regex(/^[A-Z][A-Z0-9-]*$/, 'a reason tag is UPPER-KEBAB (DAMIT-MASTER)');
const OneLine = (what: string) =>
  z.string().refine((value) => !/[\r\n]/.test(value), `${what} must be one line`);

/**
 * One ignore pattern. No leading or trailing space (git trims trailing space, so it would not match what it says), no
 * newline, and not a comment (a leading `#` would be one: escape it `\#`).
 */
export const GitignorePattern = OneLine('a pattern')
  .refine((p) => p.length > 0, 'a pattern is not empty')
  .refine((p) => p === p.trim(), 'a pattern has no leading or trailing space')
  .refine((p) => !p.startsWith('#'), 'a pattern starting with # is a comment; write \\#');

/** A brand's own rule, kept in its `fli.brand.json` (`gitignore: [...]`) so it travels with the repo. */
export const GitignoreOverlayRule = z.object({
  pattern: GitignorePattern,
  reason: Tag,
  note: OneLine('a note').optional(),
});
export type GitignoreOverlayRule = z.infer<typeof GitignoreOverlayRule>;

export const GitignoreGroup = z.object({
  reason: Tag,
  note: z.string(),
  patterns: z.array(z.string()),
});
export type GitignoreGroup = z.infer<typeof GitignoreGroup>;

const exts = (...e: string[]) => e.map((x) => `*.${x}`);

/** The base rules, denies first and re-includes after (see the file note). Every brand gets all of them. */
export const GITIGNORE_BASE: readonly Readonly<GitignoreGroup>[] = [
  {
    reason: 'DAMIT-MASTER',
    note: 'Video masters never go in git (DAMit: metadata stays in git, masters do not).',
    patterns: exts('mp4', 'mov', 'avi', 'mkv', 'flv', 'wmv', 'webm'),
  },
  {
    reason: 'DAMIT-MASTER',
    note: 'Audio masters (R2, 2026-10-05).',
    patterns: exts('wav', 'mp3', 'm4a', 'aac', 'flac'),
  },
  {
    reason: 'DAMIT-MASTER',
    note: 'Large raw assets.',
    patterns: exts('psd', 'ai', 'sketch'),
  },
  {
    reason: 'DAMIT-MASTER',
    note: 'Archives (Skool zips are built from source, never committed: R5).',
    patterns: ['*.zip', '*.tar', '*.tar.gz', '*.rar'],
  },
  {
    reason: 'TIER-CACHE',
    note: 'Renders and trash are a cache: regenerable or disposable (R2). Directory rules, so nothing inside can be re-included.',
    patterns: ['-renders/', '-trash/'],
  },
  {
    reason: 'TIER-CACHE',
    note: 'Build output.',
    patterns: ['node_modules/', '.next/', 'dist/', 'build/', '.cache/', '*.log'],
  },
  {
    reason: 'TIER-CACHE',
    note: 'Motion machinery (R1/R2): source under motion/ is tracked, what a render leaves behind is not.',
    patterns: ['**/motion/**/out/', '**/motion/**/.transcode-cache/'],
  },
  {
    reason: 'LEGACY-DENY',
    note: 'Stray app code in a video repo; kept so the motion re-include below makes sense.',
    patterns: [
      'code/',
      ...exts('tsx', 'ts', 'jsx', 'js', 'css'),
      '!package.json',
      '!*.config.js',
      '!tsconfig.json',
    ],
  },
  {
    reason: 'OS',
    note: 'Operating-system litter.',
    patterns: [
      '.DS_Store',
      'Thumbs.db',
      '*.swp',
      '*.swo',
      '*~',
      'desktop.ini',
      '*:Zone.Identifier',
    ],
  },
  {
    reason: 'GENERATED',
    note: 'Gallery output.',
    patterns: ['.mochaccino/'],
  },
  {
    reason: 'TIER-SOURCE',
    note: 'Motion source is tracked (R1). After the code deny above.',
    patterns: ['ts', 'tsx', 'jsx', 'js', 'css'].map((e) => `!**/motion/**/*.${e}`),
  },
  {
    reason: 'TIER-SOURCE',
    note: 'Small assets and thumbnails.',
    patterns: ['jpg', 'jpeg', 'png', 'gif', 'svg'].map((e) => `!**/assets/**/*.${e}`),
  },
  {
    reason: 'DAMIT-METADATA',
    note: 'Metadata stays in git.',
    patterns: ['md', 'json', 'txt', 'srt', 'yml', 'yaml'].map((e) => `!**/*.${e}`),
  },
  {
    reason: 'MACHINE-LOCAL',
    note: 'Per-developer configuration. Last of the base on purpose: `.claude/settings.local.json` is JSON, so the metadata re-include above would otherwise win (v-voz held it only by accident of order).',
    patterns: ['.video-tools.env', '**/.claude/settings.local.json'],
  },
];

/** Every pattern line the base and an overlay would emit, for duplicate detection. */
function groupsFor(overlay: readonly GitignoreOverlayRule[]): GitignoreGroup[] {
  const groups: GitignoreGroup[] = [...GITIGNORE_BASE];
  // Consecutive rules with one reason and note share a header, in the order the brand wrote them.
  for (const rule of overlay) {
    const last = groups[groups.length - 1];
    const note = rule.note ?? '';
    if (
      groups.length > GITIGNORE_BASE.length &&
      last &&
      last.reason === rule.reason &&
      last.note === note
    ) {
      groups[groups.length - 1] = { ...last, patterns: [...last.patterns, rule.pattern] };
    } else groups.push({ reason: rule.reason, note, patterns: [rule.pattern] });
  }
  return groups;
}

export interface GitignoreRenderOptions {
  /** The brand key (`aitldr`), as in `fli.brand.json`. Named in the marker; no path, host or user ever is. */
  brand: string;
  overlay?: readonly GitignoreOverlayRule[];
}

/**
 * The generated block, `BEGIN … END`, LF line endings, ending with a newline. Throws on an invalid overlay rule or a
 * brand key with a newline.
 */
export function renderGitignoreBlock(options: GitignoreRenderOptions): string {
  const overlay = z.array(GitignoreOverlayRule).parse(options.overlay ?? []);
  const brand = OneLine('brand').parse(options.brand);
  const lines = [
    `${GITIGNORE_BEGIN} (base v${GITIGNORE_BASE_VERSION}, brand ${brand}) - DO NOT EDIT BETWEEN THE MARKERS`,
    '# Change the rules in fli-core (base) or in this brand\'s fli.brand.json "gitignore" (overlay), then re-render.',
  ];
  for (const group of groupsFor(overlay)) {
    lines.push('', group.note === '' ? `# [${group.reason}]` : `# [${group.reason}] ${group.note}`);
    lines.push(...group.patterns);
  }
  lines.push(GITIGNORE_END, '');
  return lines.join('\n');
}

/** The pattern lines (not comments) of a block's text. */
export function patternLines(text: string): string[] {
  return text
    .split(/\r?\n/)
    .map((line) => line.trimEnd())
    .filter((line) => line !== '' && !line.startsWith('#'));
}

interface Located {
  /** Offset of the BEGIN line's first character. */
  start: number;
  /** Offset just past the END line's newline (or the end of the file). */
  end: number;
}

export type BlockLocation =
  { kind: 'none' } | { kind: 'broken'; message: string } | ({ kind: 'found' } & Located);

/** Find the one generated block. Two BEGINs, a BEGIN with no END, an END with no BEGIN, or END before BEGIN: `broken`. */
export function locateBlock(text: string): BlockLocation {
  const begins: number[] = [];
  const ends: { start: number; end: number }[] = [];
  let offset = 0;
  while (offset <= text.length) {
    const nl = text.indexOf('\n', offset);
    const stop = nl === -1 ? text.length : nl + 1;
    const line = text.slice(offset, nl === -1 ? text.length : nl).replace(/\r$/, '');
    if (line.startsWith(GITIGNORE_BEGIN)) begins.push(offset);
    else if (line === GITIGNORE_END) ends.push({ start: offset, end: stop });
    if (nl === -1) break;
    offset = stop;
  }
  if (begins.length === 0 && ends.length === 0) return { kind: 'none' };
  if (begins.length > 1)
    return { kind: 'broken', message: `${begins.length} BEGIN markers (expected 1)` };
  if (ends.length > 1)
    return { kind: 'broken', message: `${ends.length} END markers (expected 1)` };
  if (begins.length === 0) return { kind: 'broken', message: 'an END marker with no BEGIN' };
  if (ends.length === 0) return { kind: 'broken', message: 'a BEGIN marker with no END' };
  const begin = begins[0] as number;
  const end = ends[0] as { start: number; end: number };
  if (end.start < begin)
    return { kind: 'broken', message: 'the END marker comes before the BEGIN' };
  return { kind: 'found', start: begin, end: end.end };
}

/** The base version a block's marker names, or null (an older or hand-made marker). */
export function markerVersion(blockText: string): number | null {
  const match = /\(base v(\d+),/.exec(blockText.split(/\r?\n/, 1)[0] ?? '');
  return match ? Number(match[1]) : null;
}

export const GitignoreRenderResult = z.object({
  status: z.enum(['created', 'updated', 'unchanged', 'refused']),
  /** The whole file after the render (the existing text, untouched, when refused). */
  content: z.string(),
  /** Lines in the new block that were not in the old one. */
  added: z.array(z.string()),
  /** Lines in the old block that are not in the new one. */
  removed: z.array(z.string()),
  /** Hand-written pattern lines outside the block that the block now also emits: reported, never deleted. */
  legacyDuplicates: z.array(z.string()),
  /** The block is not the last thing in the file: a hand rule after it could undo a re-include. Reported, not moved. */
  blockNotLast: z.boolean(),
  /** Why a render was refused: the markers are broken. */
  message: z.string().optional(),
});
export type GitignoreRenderResult = z.infer<typeof GitignoreRenderResult>;

function lineDiff(before: string, after: string): { added: string[]; removed: string[] } {
  const count = new Map<string, number>();
  for (const line of before.split('\n')) count.set(line, (count.get(line) ?? 0) + 1);
  const added: string[] = [];
  for (const line of after.split('\n')) {
    const n = count.get(line) ?? 0;
    if (n > 0) count.set(line, n - 1);
    else added.push(line);
  }
  const removed: string[] = [];
  for (const [line, n] of count) for (let i = 0; i < n; i += 1) removed.push(line);
  const keep = (l: string) => l.trim() !== '';
  return { added: added.filter(keep), removed: removed.filter(keep) };
}

function handLines(
  text: string,
  block: Located | null,
): { dupes: (generated: Set<string>) => string[]; notLast: boolean } {
  const outside = block === null ? text : text.slice(0, block.start) + text.slice(block.end);
  const after = block === null ? '' : text.slice(block.end);
  return {
    notLast: patternLines(after).length > 0,
    dupes: (generated) => [...new Set(patternLines(outside).filter((line) => generated.has(line)))],
  };
}

/**
 * Render the block into a `.gitignore`'s text. `existing` is the file as it is (`null`/`''` when there is none).
 *   - No block yet: the block is appended at the end after a blank line; hand lines are kept as they are and any that
 *     the block now also emits are listed in `legacyDuplicates` (never deleted without a person's say).
 *   - A block: replaced in place; every byte outside the markers is untouched.
 *   - Broken markers (two BEGINs, no END…): `refused`, nothing changes.
 * Deterministic and idempotent: rendering its own output returns `unchanged`.
 */
export function renderGitignore(
  existing: string | null,
  options: GitignoreRenderOptions,
): GitignoreRenderResult {
  const text = existing ?? '';
  const block = renderGitignoreBlock(options);
  const located = locateBlock(text);
  if (located.kind === 'broken') {
    return {
      status: 'refused',
      content: text,
      added: [],
      removed: [],
      legacyDuplicates: [],
      blockNotLast: false,
      message: `The generated block is damaged (${located.message}); fix it by hand first. Nothing was written.`,
    };
  }
  const generated = new Set(patternLines(block));
  if (located.kind === 'found') {
    const content = text.slice(0, located.start) + block + text.slice(located.end);
    const hand = handLines(text, located);
    const diff = lineDiff(text.slice(located.start, located.end), block);
    return {
      status: content === text ? 'unchanged' : 'updated',
      content,
      added: diff.added,
      removed: diff.removed,
      legacyDuplicates: hand.dupes(generated),
      blockNotLast: hand.notLast,
    };
  }
  const head = text === '' ? '' : `${text.endsWith('\n') ? text : `${text}\n`}\n`;
  const hand = handLines(text, null);
  return {
    status: text === '' && existing === null ? 'created' : 'updated',
    content: head + block,
    added: block.split('\n').filter((l) => l.trim() !== ''),
    removed: [],
    legacyDuplicates: hand.dupes(generated),
    blockNotLast: false,
  };
}

export const GitignoreCheckResult = z.object({
  /** `ok`: the block is what would be rendered. `drift`: it differs. `no-block`: never generated. `broken-markers`. */
  status: z.enum(['ok', 'drift', 'no-block', 'broken-markers']),
  /** `status === 'ok'`: the exit code of a hook or a fleet sweep is non-zero for everything else. */
  ok: z.boolean(),
  /** Lines the rendered block has that the file's does not. */
  missing: z.array(z.string()),
  /** Lines the file's block has that the rendered one does not (someone edited between the markers). */
  extra: z.array(z.string()),
  /** The base version in the file's marker, when there is one. */
  fileBaseVersion: z.number().int().nullable(),
  baseVersion: z.number().int(),
  /** Why, in a sentence, when not ok. */
  reason: z.string().optional(),
  legacyDuplicates: z.array(z.string()),
  blockNotLast: z.boolean(),
});
export type GitignoreCheckResult = z.infer<typeof GitignoreCheckResult>;

/**
 * `gitignore.render --check`: write nothing, say whether the file's block is what would be rendered. A different base
 * version is drift with that reason — never a rewrite on the spot (design §2.6: update the committed file where the
 * rules are made and let the other Mac pull).
 */
export function checkGitignore(
  existing: string | null,
  options: GitignoreRenderOptions,
): GitignoreCheckResult {
  const text = existing ?? '';
  const block = renderGitignoreBlock(options);
  const located = locateBlock(text);
  const base = {
    baseVersion: GITIGNORE_BASE_VERSION,
    missing: [] as string[],
    extra: [] as string[],
    fileBaseVersion: null as number | null,
    legacyDuplicates: [] as string[],
    blockNotLast: false,
  };
  if (located.kind === 'broken') {
    return {
      ...base,
      status: 'broken-markers',
      ok: false,
      reason: `The generated block is damaged (${located.message}).`,
    };
  }
  const generated = new Set(patternLines(block));
  const hand = handLines(text, located.kind === 'found' ? located : null);
  const legacyDuplicates = hand.dupes(generated);
  if (located.kind === 'none') {
    return {
      ...base,
      status: 'no-block',
      ok: false,
      reason: 'This .gitignore has never been generated.',
      legacyDuplicates,
    };
  }
  const actual = text.slice(located.start, located.end);
  const fileBaseVersion = markerVersion(actual);
  if (actual === block) {
    return {
      ...base,
      status: 'ok',
      ok: true,
      fileBaseVersion,
      legacyDuplicates,
      blockNotLast: hand.notLast,
    };
  }
  const diff = lineDiff(actual, block);
  const reason =
    fileBaseVersion !== GITIGNORE_BASE_VERSION
      ? `base version differs (file v${fileBaseVersion ?? '?'}, rules v${GITIGNORE_BASE_VERSION})`
      : diff.added.length === 0 && diff.removed.length === 0
        ? 'the block differs in line endings or marker text'
        : 'someone edited between the markers, or the overlay changed';
  return {
    ...base,
    status: 'drift',
    ok: false,
    reason,
    missing: diff.added,
    extra: diff.removed,
    fileBaseVersion,
    legacyDuplicates,
    blockNotLast: hand.notLast,
  };
}
